### ISSUE TITLE
Please change the decribtion of this plugin.

### ISSUE THREAD

**Issue by wsdjeg** [c9s/perlomni.vim#24]
Hi @c9s , I am author of [SpaceVim](https://github.com/SpaceVim/SpaceVim), this is someting like spacemacs but for vim, and I want to add this plugin to lang/perl layer. I get this plugin by google, but in github, when I search `perl omni`, this plugin will not be listed, I hope you can change the describtion to 
```
perl omni completion for vim (including base class function compleltions .. etc) 
```
then I think searching `perl omni` will works.

thanks.

**Comment by c9s** [comment]
Thanks. Nice work

Will do.

Best
c9s


Wang Shidong <notifications@github.com>於 2017年1月25日 週三，21:33寫道：

**Comment by wsdjeg** [comment]
@c9s 
Maybe we can use func like `perlomni#complete()` for omni func, autoload func is better than global function begin with a capital letter.
for example , I have a plugin named foo. then `foo#Test()` should only be defined in my plugin, if I use `Test()`, it maybe override by other plugins.

this is why I create SpaceVim, instead of join space-vim.

you can have a look at https://github.com/SpaceVim/SpaceVim/issues/9, now space-vim just do same thing as me, move all functions to autoload diretory.  😆
